eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8090

spring:
  application:
    name: students
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testing
    username: root
    password: '#Sengseyha05'
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true


